services:
- docker

# before_install:
# - docker build --target development --tag todo-app:dev .
# - docker run --env-file ./.env -p 5000:5000 --mount type=bind,source="$(pwd)"/todo_app,target=/app/todo_app/ todo-app:dev
# - docker ps -a 

script:
- docker build --target test --tag todo-app:test .
-docker run --mount type=bind,source="$(pwd)"/,target=/app/ todo-app:test tests/test_view_model.py
