services:
- docker
script:
- docker build --target test --tag todo-app:test .
#- docker run --mount type=bind,source="$(pwd)"/,target=/app/ todo-app:test tests/test_view_model.py
#- docker run --mount type=bind,source="$(pwd)"/,target=/app/ todo-app:test tests/test_endpoints.py
- docker run --mount type=bind,source="$(pwd)"/,target=/app/ todo-app:test tests_e2e
