services:
- docker
script:
- docker build --target test --tag todo-app:test .
- docker run --mount type=bind,source="$(pwd)"/,target=/app/ todo-app:test tests/test_view_model.py
- docker run --mount type=bind,source="$(pwd)"/,target=/app/ todo-app:test tests/test_endpoints.py
- docker run --mount type=bind,source="$(pwd)"/,target=/app/ todo-app:test tests_e2e
#env:
#  global:
    #- secure: gcAdaF0U8LmJuOctzL3TPgeC0tRUqKWtWYkn7TNc9PRHE+aJnNeKe2DPJgQBtKeC31YdOs52tcvKretZapD/DqJYyuCcXFTDns362ie3uu70nruYrC/FKFWTfUI7ACMWlQLGZc/YMP4NmlF1nm/SDaRiSBKF/lL48X6Qwtigq2Ylkz0u5Lp5AuBlaYeB0sWLjqIYvRCWJPeLQeDTIaH/yT/gV5nJVx+CSnLVSnbnX/EZYFWLeXLbYi8zVW7fRyrjacHOK0BRrrS7oPKhQ7ZcBF0PYjFhvbQupDRVsZB35/xuPReX/IMtJMonQbuLnm7tH6LT8kpHbRdCgTs4ZhicUr6/bwk/UIBluW/5sHgKxmoK4gi+4HJ6kfGAa2T6kpAlzpOci3eetshmbI1V5+AXwrIGq01igayseOqCgpH81r1ZbnVSzdhIAIEgVz0vXpG8huqVny1YlVdFM81+EOzQ8lHYgUNAr+SeDZsQ0JggvbuNlluasZCotm/b0+y9HLtSeIqJuXCV8XEoPXwoo/crlyZ5xHkX6++Qe9clQl/ynXa2TAkYBHg0TVqlJU4iUCo1SeVWmKdJGkkxWUz2wsUpJVbu9+gCb0hIs0lfXq8aZomdcAcyOAbFdHxWPKcrjsvv95rLvYE6E5C2J/Bz7F6Zgu1ANdPQ1Qtged24MRkyVpU=
    #- secure: led7vSM89864H/1BGEHf5rm/gnJA1fj05Y+FHF5aI/OWo9AK+9DQ4aqjmHqcuyYAwTM8TNmsXIG3h80B1GeCz3KP1Zt7uiaTBsg70lVgrurcOsLdg5UfW7oEOC2elC2Bvy7gYIpFVEFHt2s9/cmtSOybmOJ5kEc2JnN0Zsd/+bJ7opMX40hAg74HpGDxv8z/CM3Q/sVx7vzYoX6Vv9M0uW7gth/U0X3SWOnMFWg98wVvHD27bTDcAxk5wROx9RuU5eXvshh+aLScUXWHoMKD90BP1nThKAiWHJZcozX2otJyiiKghMIeo03RiuKY0V3BC+eS4KmVfmhzuBEd2VlWssPnVnBhmRvbn1RnBV8ahXul4afCVUfzcmTZRIVZMkdoqEpaAFMtiiXxrw54rMJnNYn1yWN8Us5JWQtNgT612g4SRiwYe9CEIO9t1xGjl9plqbnwoDfYKYzKQFzMqYksJojsH5e5l/NaQb36SHIganrWAAxyh4vfCw+ClEjEzEsJkQOYC0fms7S+eytRlb3mMALQJ6CdS4wl1Vq4lY+18ern3CkPy7s8scT/FqYOeL8Ko1vGBCMxypj6PiqPHaOzSRap2f+Y+RBK2K/UBMZyhbgSmj11Oc0ebIEdaCuole8dQk+zhl0uqqfnaXkmE/BR8dcVxCCOJJxsNPn6FHkyObQ=
    #- FLASK_APP=todo_app/app
    #- FLASK_ENV=development
    #- FLASK_SKIP_DOTENV=FALSE
#jobs:
#     - FLASK_SKIP_DOTENV=False
#     - TRELLO_BOARD_ID=5feb252a40ff2d09fa3a8eea
